### ISSUE TITLE
Unable to upload 

### ISSUE THREAD

**Issue by taf2** [HubSpot/ui-extensions-examples#19]
[ERROR] The request in account 24392584 was forbidden. Failed to perform the action. `24392584` does not have access to this feature. Contact HubSpot support for assistance.
✖ Failed to upload ctm-hubspot-text project files to ctm-dev (24392584)
[ERROR] The post in account 24392584 was forbidden. Failed to perform the action. `24392584` does not have access to this feature. Contact HubSpot support for assistance.

**Comment by sejal27** [comment]
Hello @taf2 , to be able to use this recipes, please see if the following conditions are true

1. You are using a HubSpot account with Sales/Service Hub enterprise access
2. You are a super admin for that account.
3. You have enroled into the CRM development beta, using **Product updates > Betas** section.

**Comment by taf2** [comment]
@sejal27 a developer account?

**Comment by sejal27** [comment]
@taf2 this is not available on developer account. Only accounts with Sales or Service Hub enterprise tiers. Are you a working with HubSpot partner or customer?

**Comment by taf2** [comment]
@sejal27 that's very annoying - for salesforce i've had a developer account for 10 years and been able to maintain multiple applications... really would be great if HubSpot considered a more developer friendly ecosystem like Salesforce has built... I may come back to this when time permits but this is a real turn off.
