### ISSUE TITLE
hubspotscore is a read only property and will cause issues when trying to use this extensions

### ISSUE THREAD

**Issue by cmartin-hs** [HubSpot/ui-extensions-examples#77]
**Describe the bug**
if you deploy the duplicate-contact extension, you'll get an error because hubspotscore is a read-only property
**To Reproduce**
just deploy the duplicate-contact extension and if you try to duplicate a contact you'll get the 400 bad request error
**Expected behavior**
it's not unexpected to get this error since hubspotscore is a read-only property

**Comment by atanasiuk-hubspot** [comment]
Fixed in https://github.com/HubSpot/ui-extensions-examples/pull/80
